title: "Guía NotebookLM"
remote_theme: pmarsceill/just-the-docs

# Enlaces para editar en GitHub
gh_edit_repository: "https://github.com/ernestobarrera/notebooklm"
gh_edit_link: true
gh_edit_link_text: "Editar esta página en GitHub"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

# Información de licencia
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "http://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# Enlaces auxiliares (puedes añadir los que desees)
aux_links:
  "Repositorio original de Uvic Libraries":
    - "https://github.com/uviclibraries/genai-notebooklm"

aux_links_new_tab: true

# Pie de página y otros textos
back_to_top: true
back_to_top_text: "Volver arriba"

footer_content: "<img src=\"https://i.creativecommons.org/l/by/4.0/88x31.png\" style=\"float:right;\">
Copyright &copy; 2025 Ernesto Barrera<br>
Adaptado de <a href=\"https://uvic.ca/library/dsc/\">UVic Libraries Digital Scholarship Commons</a> bajo <a href=\"http://creativecommons.org/licenses/by/4.0/\">Creative Commons Attribution 4.0 International License.</a>"

# Timestamp de última edición
last_edit_timestamp: true
last_edit_time_format: "%d %b %Y %H:%M"

# Plugins opcionales
plugins:
  - jekyll-seo-tag

# Idioma del sitio 
lang: "es"
